language: node_js
node_js:
- node
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: YlRWE+sUzzV0UrntTBcOf9ag1LINpPHzVYO7K5GD6TDERiwNvqKW1uHw9pMjwzmeERcmr1VM9YZgO9ohyka4ZRvyH7PZLO3/jIMRgxW36nnUYEjSLvMlKDCp0SWfJ1LOLVpnmMpD4x9EU8WZDbyiAWS26pBUD8StsYFGUAlaGip2ahZvbqlXOQW3TQpKhHZ8xI6qDZ8ufYvJuWFH35vi6jDGd6x+ZEHVlt8rxJXR0uhc0TmrVvWoBqe+48s8rkCcmrKCpzy4y5xZJnju59SRSUrk4b+W+vcZGmDGUfOeKxXB7xjtrILtBpDO16BrJpfaJRBje5nBM/DUstaCGl+K8Zjp5smBbHv8i+rivA3xdiUBOLy2+bYpe9Umoc+9noUqCtC5d0u5TjsH0DmKhQGacogeQ0ZgdN68UkOeQiirqsqXj+bxvN6EaxgQUPFbHodghr1NnTLPJyFqsS9IHXs7lSY6Bh+TCr+B6+unxp47RFLjmae9UrOaL4hrDcM+vzfgTIcn9XbBqdcY6nu5ydA4fbJaUeIemgpI0ircfQsEERcHm/m8Uyt+RCIuUl/uu0AkW9ItI3dSZk370ll40PYDHwo4DjqxLvm2nzDBl03JypQiH87x9wZ9CfEAP5IIQr6blsLEYiZy8ZDPWaRJPCxruB+6JZRiccPWlS8nlvCxO6k=
